version: '3.3'

services:

  frontend:
    build: ./All/frontend
    image: thatchon/webfrontend:1.0
    ports:
      - "3000:3000"

  backend:
    build: ./All/backend
    image: thatchon/webbackend:1.0
    ports:
      - "3005:3000"